### ISSUE TITLE
Add `Edit+Delete` permission in sharing a data folder to other users

### ISSUE THREAD

**Issue by adrysn** [lablup/backend.ai-webui#1320]
In the "Modify Permissions" panel for a shared data folder, the folder owner can change the invitees' permission. Currently, the available permissions are `View`, `Edit`, and `Edit+Delete` except `Kick out user`.
<img width="642" alt="image" src="https://user-images.githubusercontent.com/7539358/170599684-26e3304e-23c6-46d4-90b9-f27a6af9e2dd.png">

In the "Share Foder" panel, however, there are only two permissions: `View` and `Edit`. It would be logical that the available permissions are the same in sharing and modifying. I suggest adding the `Edit+Delete` permission in the initial sharing process.
<img width="380" alt="image" src="https://user-images.githubusercontent.com/7539358/170600516-b38bc9c4-8317-4297-94cc-0a0f8add1aa8.png">

**Comment by AshwinNema** [comment]
@adrysn I'm new to open-source contribution and I'm interested by your issue. Can I take up this issue?

**Comment by adrysn** [comment]
> @adrysn I'm new to open-source contribution and I'm interested by your issue. Can I take up this issue?

Great! Please take this issue and let me know if there are any updates. Thanks.

**Comment by AshwinNema** [comment]
@adrysn  I forked the project and tried doing npm i but I got this error, ![Screenshot (31)](https://user-images.githubusercontent.com/72392780/170851307-06a0bbdf-ce3c-4509-b90a-009144a14c59.png) 
 I am using windows 10 64-bit with latest version of npm. Any idea how to resolve this issue?

**Comment by AshwinNema** [comment]
@adrysn  Can you please share default configuration for config.toml for setting it up in my local system

**Comment by AshwinNema** [comment]
@adrysn Can you please share default configuration for config.toml for setting it up in my local system. I am using windows-10 64 bits

**Comment by AshwinNema** [comment]
@adrysn  I am getting this error when I am doing npm run server:d. I am using windows-10 64 bit.
Can you please advice on how to resolve this issue
 ![Screenshot (35)](https://user-images.githubusercontent.com/72392780/170865724-962c3daf-b2b6-49f3-8953-c18a1c7ed8b0.png)

**Comment by adrysn** [comment]
Because I don't use Windows in my development environment, I'm not sure what caused the error. However, based on the error message `'.' is not recognized as an internal or external command,` it appears that the `.` command is not supported by the Windows terminal. (In bash, `.` is the command that evaluates another command in the current context.) Why don't you check the'server:d' execution step from the 'package.json' to see where '.' is used. Alternatively, you may use WSL2 or VM to set up a Linux development environment.

Reference for the `.` command: https://www.shell-tips.com/bash/source-dot-command/#gsc.tab=0

**Comment by AshwinNema** [comment]
@adrysn  I used WSL2 to set up a Linux development environment and did npm i. Now I am getting this error. Can you please suggest to me how can I fix this issue?
![Screenshot (37)](https://user-images.githubusercontent.com/72392780/171033735-07d3493b-334b-4d12-b99f-9784a3daa8cb.png)

**Comment by adrysn** [comment]
Perhaps, the links below might help?
* https://pakstech.com/blog/npm-no-such-file/
* https://stackoverflow.com/questions/71403788/how-to-run-npm-command-correctly-in-wsl

**Comment by AshwinNema** [comment]
> Perhaps, the links below might help?
> 
> * https://pakstech.com/blog/npm-no-such-file/
> * https://stackoverflow.com/questions/71403788/how-to-run-npm-command-correctly-in-wsl

It helped. Thank you for the links above

**Comment by AshwinNema** [comment]
@adrysn  I tried making some changes in the project but my git is not showing changes which I have made. But when I close my 
vs code and reopen it all the changes are reflected. I referred to this issue https://github.com/microsoft/vscode-remote-release/issues/314 Unfortunately could not find anything here. Is there any way I can fix this issue?

**Comment by adrysn** [comment]
Sorry, but I cannot help you with the VSCode issue since I don't know.

1. My `config.toml` looks like below:
```toml
[general]
apiEndpoint = "http://127.0.0.1:9004"
siteDescription = "Dev Server"
connectionMode = "SESSION"
allowChangeSigninMode = true
signupSupport = true
allowSignout = false
allowProjectResourceMonitor = true
allowManualImageNameForSession = false
debug = false

[wsproxy]
proxyURL = "http://127.0.0.1:5050/"
#proxyBaseURL = ""
disableCertCheck = false

[menu]
#blocklist = ""

[resources]
openPortToPublic = true
maxCPUCoresPerContainer = 32
maxMemoryPerContainer = 16
maxCUDADevicesPerContainer = 16
maxCUDASharesPerContainer = 16
maxShmPerContainer = 8
maxFileUploadSize = 4294967296

[environments]
#allowlist = ""

[server]
# webServerURL = "http://10.20.30.10:9004"

[plugin]
```
2. You can fork this repository and create your own branch. For example, `fix/consistent-permission-for-sharing-data-folder`. When you are done, you can create a PR from the branch.
3. The API endpoint should point to a Backend.AI Webserver. To launch a development server for Backend.AI, please refer to the link: https://github.com/lablup/backend.ai#getting-started.
