### ISSUE TITLE
Let's modify components so that the color/font changes along with the theme.

### ISSUE THREAD

**Issue by agatha197** [lablup/backend.ai-webui#1838]
### Main idea

Replace hard-coded color and font-related css with general variables.
We can change the webui theme with `resources/custom.css`. Some buttons, switches, tabs, etc. are hardcoded and don't change even if the theme is changed. For example, [`--mdc-theme-primary` etc. is hardcoded.](https://github.com/lablup/backend.ai-webui/blob/main/src/components/backend-ai-environment-list.ts#L193) So even if the theme is changed, the color of this button does not change.
Therefore, find something hard-coded like this and replace it with `--general-<variable>`.

### Anything else?

Here is an example of the `resources/custom.css`.
```css
:host > *, html {
  --general-font-family: <font-family> !important;
  --general-textfield-selected-color: <color>!important;
  --general-textfield-idle-color: <color>!important;
  --general-button-color: <color>;
  --general-switch-off-color: <color>;
  --general-switch-on-color: <color>;
  --general-switch-on-background-color: <color>;
  --general-sidebar-topbar-color: <color> !important;
  --general-sidebar-background-color: <color> !important;
  --general-button-background-color: <color> !important;
  --general-progress-bar-bg: <color>;
}
```
